// Builds the member's career-ops portals.yml (what the Scout scans) from a
// simple list of companies + title keywords. Pure — tested.
export interface PortalCompany { name: string; careersUrl: string; enabled?: boolean }
export interface PortalsInput { companies: PortalCompany[]; positive: string[]; negative: string[] }

const q = (v: unknown) => JSON.stringify(String(v ?? "").trim());
export const MAX_COMPANIES = 25;

export function normalizeUrl(raw: string): string | null {
  const s = raw.trim();
  if (!s) return null;
  try { const u = new URL(/^https?:\/\//i.test(s) ? s : `https://${s}`); return /^https?:$/.test(u.protocol) && u.hostname.includes(".") ? u.toString() : null; }
  catch { return null; }
}

export function buildPortalsYaml({ companies, positive, negative }: PortalsInput): string {
  const cos = companies
    .map((c) => ({ name: c.name.trim(), url: normalizeUrl(c.careersUrl), enabled: c.enabled !== false }))
    .filter((c): c is { name: string; url: string; enabled: boolean } => !!c.name && !!c.url)
    .slice(0, MAX_COMPANIES);
  const pos = positive.map((k) => k.trim()).filter(Boolean);
  const neg = negative.map((k) => k.trim()).filter(Boolean);
  const lines = [
    "# Generated by JobHacker Compass (Agents → Setup → Portals). Edit there, not here.",
    "title_filter:",
    "  positive:",
    ...(pos.length ? pos.map((k) => `    - ${q(k)}`) : ["    []"]),
    "  negative:",
    ...(neg.length ? neg.map((k) => `    - ${q(k)}`) : ["    []"]),
    "tracked_companies:",
    ...(cos.length ? cos.flatMap((c) => [`  - name: ${q(c.name)}`, `    careers_url: ${q(c.url)}`, `    enabled: ${c.enabled}`]) : ["  []"]),
  ];
  return lines.join("\n") + "\n";
}

// Sensible starting keywords from the member's goal role: "Senior Product Owner" → ["Product Owner", "Product Manager"].
export function suggestKeywords(role: string | undefined): string[] {
  const r = (role ?? "").replace(/^(intern|junior|graduate|mid|senior|staff|principal|lead|head of|director of|vp of)\s+/i, "").trim();
  if (!r) return [];
  const out = [r];
  if (/product owner/i.test(r)) out.push("Product Manager");
  if (/product manager/i.test(r)) out.push("Product Owner");
  return out;
}

export const DEFAULT_NEGATIVE = ["Junior", "word:Intern", "Internship", "Graduate"];
