// Builds the member's career-ops portals.yml (what the Scout scans) from a
// simple list of companies + title keywords. Pure — tested.
export interface PortalCompany { name: string; careersUrl: string; enabled?: boolean }
export interface PortalsInput { companies: PortalCompany[]; positive: string[]; negative: string[] }

const q = (v: unknown) => JSON.stringify(String(v ?? "").trim());
export const MAX_COMPANIES = 25;

export function normalizeUrl(raw: string): string | null {
  const s = raw.trim();
  if (!s) return null;
  try { const u = new URL(/^https?:\/\//i.test(s) ? s : `https://${s}`); return /^https?:$/.test(u.protocol) && u.hostname.includes(".") ? u.toString() : null; }
  catch { return null; }
}

export function buildPortalsYaml({ companies, positive, negative }: PortalsInput): string {
  const cos = companies
    .map((c) => ({ name: c.name.trim(), url: normalizeUrl(c.careersUrl), enabled: c.enabled !== false }))
    .filter((c): c is { name: string; url: string; enabled: boolean } => !!c.name && !!c.url)
    .slice(0, MAX_COMPANIES);
  const pos = positive.map((k) => k.trim()).filter(Boolean);
  const neg = negative.map((k) => k.trim()).filter(Boolean);
  const lines = [
    "# Generated by JobHacker Compass (Agents → Setup → Portals). Edit there, not here.",
    "title_filter:",
    "  positive:",
    ...(pos.length ? pos.map((k) => `    - ${q(k)}`) : ["    []"]),
    "  negative:",
    ...(neg.length ? neg.map((k) => `    - ${q(k)}`) : ["    []"]),
    "tracked_companies:",
    ...(cos.length ? cos.flatMap((c) => [`  - name: ${q(c.name)}`, `    careers_url: ${q(c.url)}`, `    enabled: ${c.enabled}`]) : ["  []"]),
  ];
  return lines.join("\n") + "\n";
}

// Sensible starting keywords from the member's goal role. Keywords are case-insensitive
// SUBSTRINGS of the posting title, so short stems catch the family of titles a company
// actually uses: "Test" → Test Lead, Test Analyst, Test Automation, Testing; "QA" → QA Manager,
// QA Engineer. "Senior Product Owner" → ["Product Owner", "Product Manager"].
const FAMILIES: { when: RegExp; add: string[] }[] = [
  { when: /\b(qa|test(ing|er)?|quality)\b/i, add: ["Test", "QA", "Quality Engineer", "Quality Assurance"] },
  { when: /product owner/i, add: ["Product Manager"] },
  { when: /product manager/i, add: ["Product Owner"] },
  { when: /\bscrum master|delivery (lead|manager)|agile coach/i, add: ["Scrum Master", "Delivery Lead", "Delivery Manager", "Agile Coach"] },
  { when: /\bdata (analyst|scientist|engineer)/i, add: ["Data Analyst", "Data Engineer", "Analytics"] },
  { when: /\b(software|frontend|front-end|backend|back-end|full[- ]?stack) (engineer|developer)/i, add: ["Software Engineer", "Developer"] },
  { when: /\bbusiness analyst/i, add: ["Business Analyst", "BA "] },
  { when: /\b(engineering|tech(nical)?) (manager|lead)|chapter lead/i, add: ["Engineering Manager", "Chapter Lead", "Technical Lead"] },
];
export function suggestKeywords(role: string | undefined): string[] {
  const r = (role ?? "").replace(/^(intern|junior|graduate|mid|senior|staff|principal|lead|head of|director of|vp of)\s+/i, "").trim();
  if (!r) return [];
  const out = [r];
  for (const f of FAMILIES) if (f.when.test(role ?? "")) out.push(...f.add);
  return Array.from(new Set(out.map((k) => k.trim()).filter(Boolean)));
}

export const DEFAULT_NEGATIVE = ["Junior", "word:Intern", "Internship", "Graduate"];
