// Builds the member's career-ops config/profile.yml from what Compass already
// knows (Profile + Goal) so nobody fills in a YAML file by hand. Pure — tested.
import type { Profile } from "@/lib/types";
import type { Goal } from "@/lib/goal";

const q = (v: unknown) => JSON.stringify(String(v ?? "").trim()); // JSON strings are valid YAML scalars

export interface ProfileYamlInput {
  profile: Pick<Profile, "email" | "firstName" | "lastName" | "country"> | null | undefined;
  goal: Goal | null | undefined;
  /** Optional extra lines the member adds in Setup (e.g. visa, remote preference). */
  notes?: string;
}

export function buildProfileYaml({ profile, goal, notes }: ProfileYamlInput): string {
  const name = [profile?.firstName, profile?.lastName].filter(Boolean).join(" ").trim();
  const role = goal?.role?.trim() ?? "";
  const lines = [
    "# Generated by JobHacker Compass from your Profile and Compass goal.",
    "# Edit your goal on the Compass tab — this file follows it.",
    "candidate:",
    `  full_name: ${q(name)}`,
    `  email: ${q(profile?.email)}`,
    `  location: ${q(goal?.city || profile?.country)}`,
    "target_roles:",
    "  primary:",
    ...(role ? [`    - ${q(role)}`] : ["    []"]),
    "  archetypes:",
    ...(role ? [`    - name: ${q(role)}`, `      level: ${q(seniority(role))}`, "      fit: \"primary\""] : ["    []"]),
    "narrative:",
    `  headline: ${q(role ? `${role}${goal?.subsector ? ` in ${goal.subsector}` : ""}` : "")}`,
    "compensation:",
    `  target_range: ${q(goal?.salary)}`,
    `  minimum: ${q("")}`,
    `  location_flexibility: ${q("")}`,
    "location:",
    `  country: ${q(profile?.country)}`,
    `  city: ${q(goal?.city)}`,
    ...(profile?.country ? ["  authorized_in:", `    - ${q(profile.country)}`] : []),
    "preferences:",
    `  industry: ${q(goal?.subsector)}`,
    `  company_type: ${q(goal?.companyType)}`,
  ];
  const extra = (notes ?? "").trim();
  if (extra) lines.push("notes: |", ...extra.split("\n").map((l) => `  ${l}`));
  return lines.join("\n") + "\n";
}

// "Senior Product Owner" → "Senior"; "Head of Data" → "Head"; else "".
export function seniority(role: string): string {
  const m = role.match(/^(intern|junior|graduate|mid|senior|staff|principal|lead|head|director|vp|chief)\b/i);
  return m ? m[1][0].toUpperCase() + m[1].slice(1).toLowerCase() : "";
}
