// Client-safe types for the career-ops integration (no Upstash / Firebase imports).
import type { AgentKey, CareerOpsJobStatus, CareerOpsJobType } from "./keys";

export interface CareerOpsJob {
  id: string;
  type: CareerOpsJobType;
  status: CareerOpsJobStatus;
  uid: string;                 // member the job belongs to ("admin" jobs use the admin's uid)
  payload: Record<string, unknown>;
  createdAt: number;
  createdBy: string;           // email or uid
  startedAt?: number;
  endedAt?: number;
  worker?: string;
  progress?: string;           // one-line human status, e.g. "Block D — compensation"
  log?: string;                // tail of the worker log (≤ ~12 kB), fetched per job
  result?: unknown;
  error?: string;
  cancel?: number;             // 1 when cancellation has been requested
}

export interface WorkerHeartbeat {
  id: string;
  host: string;
  pid: number;
  version: string;
  startedAt: number;
  at: number;
  current: string | null;      // job id being worked on
  pollMs: number;
  n8n: boolean;                // n8n reachable at last check
  ollama: boolean;             // Ollama reachable at last check
}

export interface OllamaModelInfo { name: string; sizeGb: number; modifiedAt: string; family?: string; params?: string }

export interface WorkerState {
  models: OllamaModelInfo[];
  agents: { key: AgentKey; n8nWorkflowId: string | null; active: boolean }[];
  datasets: { name: string; examples: number; builtAt: string }[];
  gpu: { host: string | null; reachable: boolean; checkedAt: number };
  careerOpsVersion: string | null;   // ~/career-ops package.json version on the Pi
  vaultPublicKey?: string | null;    // RSA-OAEP public key (SPKI, base64) — the browser encrypts portal passwords for this worker
  drive?: { configured: boolean; account: string | null; folderId: string | null; ok?: boolean; name?: string; canWrite?: boolean; error?: string };
  claude?: { configured: boolean; model: string; via?: "api" | "cli" | "none"; bin?: string; hint?: string };   // via: API key · Claude Code CLI (`claude login`) · nothing
  // Non-Ollama model tags any LLM agent may run on: "claude-cli[:sonnet|opus|haiku]" (Claude Code, your
  // subscription) and "claude-api" (Anthropic key). Absent/empty when neither is set up on the Pi.
  claudeModels?: { name: string; label: string; family: "claude"; available: boolean }[];
  training?: { examples: { total: number; approved: number; exam: number; bySource: Record<string, number> }; datasets: { name: string; train: number; exam: number; builtAt: number }[] } | null;
  updatedAt: number;
}

export interface AgentConfig {
  model: string;               // Ollama tag
  numCtx: number;
  numPredict: number;          // output cap — small models ramble without one
  temperature: number;
  systemPrompt: string;
  promptVersion: number;
  promptEditedBy?: string | null;   // set once an admin edits; stops the worker auto-upgrading the default
  promptEditedAt?: number | null;
  enabled: boolean;
  n8nWorkflowId: string | null;
}

// config/agents/promptVersions/{agent}-{version} — every saved prompt, for restore.
export interface PromptVersion {
  id: string;
  agent: AgentKey;
  version: number;
  systemPrompt: string;
  savedBy: string | null;
  savedAt: number;
  note?: string;
}

// Stored at config/agents (admin write, worker read via Admin SDK).
export interface AgentsConfig {
  agents: Record<AgentKey, AgentConfig>;
  dailyEvalQuota: number;
  dailyScanQuota: number;      // Scout runs per member per UTC day (zero tokens; a browser pass can take minutes per site)
  collectLiveData: boolean;    // approved live-member reports may enter training datasets (pseudonymised)
  updatedAt?: number;
  updatedBy?: string | null;
}

export const DEFAULT_AGENT: AgentConfig = {
  model: "qwen2.5:1.5b-instruct", numCtx: 8192, numPredict: 2800, temperature: 0.2, systemPrompt: "", promptVersion: 0, enabled: true, n8nWorkflowId: null,
};

export const DEFAULT_AGENTS_CONFIG: AgentsConfig = {
  agents: {
    scout:     { ...DEFAULT_AGENT, model: "llama3.2:3b" },
    extractor: { ...DEFAULT_AGENT },
    evaluator: { ...DEFAULT_AGENT, model: "llama3.2:3b", numCtx: 8192 },
    tailor:    { ...DEFAULT_AGENT, model: "llama3.2:3b" },
    writer:    { ...DEFAULT_AGENT, model: "llama3.2:3b", temperature: 0.5 },
    researcher:{ ...DEFAULT_AGENT, model: "claude-cli", temperature: 0.3 },
  },
  dailyEvalQuota: 20,
  dailyScanQuota: 6,
  collectLiveData: false,
};

// Admin → Agents → Overview payload.
export interface AgentsStatus {
  configured: boolean;         // Upstash env present
  worker: WorkerHeartbeat | null;
  online: boolean;
  state: WorkerState | null;
  queueLength: number;
}

// ---- member data mirrored in Firestore ----

// users/{uid}/careerOps/setup — owner-writable (Firestore client SDK).
export interface CareerOpsSetup {
  cvMarkdown: string;
  profileYaml: string;      // generated by buildProfileYaml, stored for transparency
  notes?: string;
  updatedAt: number;
}

// users/{uid}/careerOpsReports/{jobId} — written by the Pi worker (Admin SDK).
export interface CareerOpsReport {
  id: string;                   // Firestore doc id (= jobId)
  jobId: string;
  n: number;
  file: string;
  company: string;
  role: string;
  url: string | null;
  title: string | null;
  score: number | null;
  archetype: string;
  legitimacy: string;
  summaryFound: boolean;
  markdown: string;
  agent: AgentKey;
  model: string;
  promptVersion: number;
  via: "n8n" | "ollama" | "claude-cli";
  usage: { prompt: number | null; completion: number | null } | null;
  durationMs: number;
  jdChars: number;
  createdAt: number;
  addedOpportunityId?: string;  // set by the client once "Add to Tracker" is used
}

export const scoreTone = (s: number | null) => s == null ? "unknown" : s >= 4.5 ? "strong" : s >= 4 ? "good" : s >= 3.5 ? "maybe" : "skip";
export const scoreVerdict = (s: number | null) =>
  s == null ? "No score" : s >= 4.5 ? "Strong match — apply now" : s >= 4 ? "Good match — worth applying" : s >= 3.5 ? "Only with a specific reason" : "Skip this one";

// ---- phase 3: Scout pipeline, Tailor / Writer documents ----

// users/{uid}/careerOps/setup also carries the Scout config.
// One watched company. careersUrl should be the page that LISTS the jobs (the ATS board when there is one),
// not the marketing "life at …" page. provider / apiUrl map 1:1 to career-ops portals.yml `provider:` / `api:`
// — needed for branded ATS domains career-ops cannot auto-detect (SuccessFactors, Phenom, …).
export interface PortalCompany { name: string; careersUrl: string; enabled?: boolean; provider?: string; apiUrl?: string }
export interface CareerOpsPortals { companies: PortalCompany[]; positive: string[]; negative: string[] }
export interface CareerOpsSetupV2 extends CareerOpsSetup { portals?: CareerOpsPortals; portalsYaml?: string }

// users/{uid}/careerOps/portalsStatus — what happened to each watchlist company on the last
// scan. Worker-written. method: "board" = career-ops read the ATS/job-board API directly;
// "page" = the Pi's browser scraped the careers page (slower, best effort); "none" = nothing worked.
// suggested: the job board the Scout found behind a marketing careers page (Workday link, branded
// SuccessFactors host, …). It was already used for that scan; "Use this" copies it onto the row so it sticks.
export interface PortalSuggestion { careersUrl: string; provider: string | null; apiUrl: string | null; live: number | null; via: "link" | "fingerprint" }
export interface PortalStatus { name: string; careersUrl: string; method: "board" | "page" | "none"; provider?: string | null; found: number; matched: number; error?: string | null; hint?: string | null; ms?: number; sample?: string[]; suggested?: PortalSuggestion }   // sample: titles seen that did NOT match the keywords
export interface PortalsStatusDoc { at: number; jobId: string; companies: PortalStatus[] }

// users/{uid}/careerOpsPipeline/{id} — postings the Scout found (worker-written, owner-updatable).
export type PipelineStatus = "pending" | "evaluated" | "dismissed";
export interface PipelineItem {
  id: string;
  url: string;
  company: string;
  title: string;
  location: string | null;
  status: PipelineStatus;
  foundAt: number;
  lastSeenAt: number;
  reportJobId?: string;
  score?: number | null;
}

// users/{uid}/careerOpsDocs/{jobId} — a tailored CV or a cover letter tied to a report.
export type DocStorage = "drive" | "bucket" | "inline";
export interface CareerOpsDoc {
  id: string;
  kind: "cv" | "cover";
  jobId: string;
  reportJobId: string;
  company: string;
  role: string;
  file: string;
  storage: DocStorage;
  driveFileId?: string | null;
  driveLink?: string | null;
  storagePath?: string | null;
  url?: string | null;         // signed URL (bucket) — may expire
  urlExpires?: number | null;
  size: number;
  pageCount: number;
  template?: string;
  words?: number;              // cover letters
  text?: string;               // cover letters — plain text for copy/paste
  keywordsUsed?: string[];
  keywordsMissing?: string[];
  model: string;
  via: "n8n" | "ollama" | "claude-cli";
  durationMs: number;
  createdAt: number;
}

// ---- phase 4: training (admin-only collections, Admin SDK writes) ----

export type ExampleSource = "claude" | "live" | "golden";
export interface TrainingExample {
  id: string;
  agent: AgentKey;
  source: ExampleSource;
  split: "train" | "exam";
  approved: boolean;
  company: string;
  role: string;
  market?: string;
  intendedFit?: string;
  notes?: string;
  cv: string;
  profileYaml: string;
  jd: string;
  report: string;
  summary: { company: string; role: string; score: number | null; archetype: string; legitimacy: string };
  teacherModel?: string;
  studentPromptVersion?: number;
  memberUid?: string;          // live examples only (pseudonymised text; uid kept for deletion requests)
  createdAt: number;
  createdBy?: string;
  jobId?: string;
}
export type TrainingExampleRow = Omit<TrainingExample, "cv" | "profileYaml" | "jd" | "report">;

export interface TrainingDataset {
  name: string;
  agent: AgentKey;
  sources: ExampleSource[];
  bySource: Record<string, number>;
  train: number;
  exam: number;
  dir: string;
  promptVersion: number;
  builtAt: number;
  builtBy?: string;
}

export interface ExamResult {
  tag: string; n: number; scored: number;
  scoreMae: number | null; within05: number | null; archetypeAgreement: number | null; legitimacyAgreement: number | null; summaryRate: number | null;
  avgSeconds: number | null; at: number; promptVersion: number;
  cases?: { id: string; company: string; role?: string; seconds?: number; gold?: { score: number | null; archetype: string }; got?: { score: number | null; archetype: string }; scoreDiff?: number | null; archetypeMatch?: boolean; error?: string }[];
}

export interface TrainingModel {
  tag: string;
  agent: AgentKey;
  source: "finetune" | "import" | "ollama";
  status: "training" | "importing" | "ready" | "failed";
  base?: string | null;
  dataset?: string;
  epochs?: number;
  exam?: ExamResult;
  error?: string;
  startedAt?: number;
  endedAt?: number;
  createdBy?: string;
}

export const FINETUNE_BASES = ["unsloth/Qwen2.5-1.5B-Instruct", "unsloth/Llama-3.2-3B-Instruct", "unsloth/Qwen2.5-3B-Instruct", "unsloth/Llama-3.2-1B-Instruct"] as const;

// ---- CareerOps portal: generic agent outputs ----

// users/{uid}/careerOpsNotes/{jobId} — every non-report, non-PDF thing an agent produces:
// a company deep-dive, an outreach DM, application answers, interview prep, a follow-up
// draft, a training/project verdict, a patterns analysis. Worker-written, owner-readable.
export type NoteKind = "deep" | "contacto" | "apply" | "apply_form" | "apply_fill" | "interview_prep" | "followup" | "training" | "project" | "patterns";
export interface CareerOpsNote {
  id: string;
  jobId: string;
  kind: NoteKind;
  title: string;
  company?: string | null;
  role?: string | null;
  reportJobId?: string | null;
  opportunityId?: string | null;
  markdown: string;             // what the member reads
  data?: Record<string, unknown>; // structured extras (answers[], dm, stats…)
  sources?: { title: string; url: string }[];   // web sources when the Researcher used search
  agent: AgentKey;
  model: string;
  via: "n8n" | "ollama" | "claude" | "claude-cli" | "claude-api" | "bank" | "script";   // bank: every answer came from the answer bank · script: no model (form reader)
  durationMs: number;
  createdAt: number;
}
export const NOTE_KIND_LABELS: Record<NoteKind, string> = {
  deep: "Company deep-dive", contacto: "Outreach", apply: "Application answers", apply_form: "Application form", apply_fill: "Filled in the portal", interview_prep: "Interview prep",
  followup: "Follow-up", training: "Training verdict", project: "Project verdict", patterns: "Patterns",
};

// users/{uid}/careerOps/followup — cadence rules per Progress-board stage (days of silence before a nudge is due).
export interface FollowupRules { days: Record<string, number>; updatedAt?: number }
export const DEFAULT_FOLLOWUP_DAYS: Record<string, number> = { outreach: 5, application: 7, info_interview: 3, job_interview: 2, offer: 2, negotiation: 3 };
export const CONTACT_TARGETS = [
  { key: "hiring_manager", label: "Hiring manager" },
  { key: "recruiter", label: "Recruiter" },
  { key: "peer", label: "Team peer" },
  { key: "interviewer", label: "Interviewer" },
] as const;
export type ContactTarget = (typeof CONTACT_TARGETS)[number]["key"];
export const PREP_AUDIENCES = [
  { key: "recruiter", label: "Recruiter screen" },
  { key: "hiring_manager", label: "Hiring manager" },
  { key: "peer", label: "Peer / technical" },
  { key: "panel", label: "Panel" },
] as const;
export type PrepAudience = (typeof PREP_AUDIENCES)[number]["key"];
