// Client-safe event tag constants. tag convention: EVENT->ACTION->TRACKER
export const TAGS = {
  REGISTRATION:    "EVENT->REGISTRATION->TRACKER",
  LOGIN:           "EVENT->LOGIN->TRACKER",
  LOGOUT:          "EVENT->LOGOUT->TRACKER",
  PASSWORD_RESET:  "EVENT->PASSWORD_RESET->TRACKER",
  LOG_ACTIVITY:    "EVENT->LOG_ACTIVITY->TRACKER",
  UNLOG_ACTIVITY:  "EVENT->UNLOG_ACTIVITY->TRACKER",
  SET_TARGET:      "EVENT->SET_TARGET->TRACKER",
  ADD_CONTACT:     "EVENT->ADD_CONTACT->TRACKER",
  LOG_INTERACTION: "EVENT->LOG_INTERACTION->TRACKER",
  ADD_OPPORTUNITY: "EVENT->ADD_OPPORTUNITY->TRACKER",
  STAGE_CHANGE:    "EVENT->OPPORTUNITY_STAGE->TRACKER",
  ADD_EVENT:       "EVENT->ADD_EVENT->TRACKER",
  PAYWALL_HIT:     "EVENT->PAYWALL_HIT->TRACKER",
  GRANT_CREATED:   "EVENT->GRANT_CREATED->TRACKER",
  GRANT_REDEEMED:  "EVENT->GRANT_REDEEMED->TRACKER",
} as const;
